language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t donwishnek/docker-reactnew -f Dockerfile.dev . 

script:
  - docker run -e CI=true donwishnek/docker-reactnew npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-reactnew"
  env: "Dockerreactnew-env"
  bucket_name: "elasticbeanstalk-us-east-1-581727867421"
  bucket_path: "docker-reactnew"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
