language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t donwishnek/docker-reactnew -f Dockerfile.dev . 

script:
  - docker run -e CI=true donwishnek/docker-reactnew npm run test -- --coverage

